const municipalitiesInBataan = [
  {
    name: "Abucay",
    barangays: [
      { name: "Bangkal", zipCode: "2114" },
      { name: "Calaylayan", zipCode: "2114" },
      { name: "Capitangan", zipCode: "2114" },
      { name: "Gabon", zipCode: "2114" },
      { name: "Laon", zipCode: "2114" },
      { name: "Mabatang", zipCode: "2114" },
      { name: "Omboy", zipCode: "2114" },
      { name: "Poblacion", zipCode: "2114" },
      { name: "Salian", zipCode: "2114" },
      { name: "Wawa", zipCode: "2114" },
    ],
  },
  {
    name: "Bagac",
    barangays: [
      { name: "Binuangan", zipCode: "2107" },
      { name: "Binukawan", zipCode: "2107" },
      { name: "Boyangin", zipCode: "2107" },
      { name: "Calaguiman", zipCode: "2107" },
      { name: "Ibaba", zipCode: "2107" },
      { name: "Ibayo", zipCode: "2107" },
      { name: "Parang", zipCode: "2107" },
      { name: "Poblacion", zipCode: "2107" },
      { name: "San Antonio", zipCode: "2107" },
      { name: "Saysayin", zipCode: "2107" },
    ],
  },
  {
    name: "Balanga City",
    barangays: [
      { name: "Barangay 1 (Pob.)", zipCode: "2100" },
      { name: "Barangay 2 (Pob.)", zipCode: "2100" },
      { name: "Barangay 3 (Pob.)", zipCode: "2100" },
      { name: "Barangay 4 (Pob.)", zipCode: "2100" },
      { name: "Barangay 5 (Pob.)", zipCode: "2100" },
      { name: "Barangay 6 (Pob.)", zipCode: "2100" },
      { name: "Barangay 7 (Pob.)", zipCode: "2100" },
      { name: "Barangay 8 (Pob.)", zipCode: "2100" },
      { name: "Barangay 9 (Pob.)", zipCode: "2100" },
      { name: "Barangay 10 (Pob.)", zipCode: "2100" },
      { name: "Bagumbayan", zipCode: "2100" },
      { name: "Bagong Silang", zipCode: "2100" },
      { name: "Banawang", zipCode: "2100" },
      { name: "Cabog-cabog", zipCode: "2100" },
      { name: "Cataning", zipCode: "2100" },
      { name: "Central", zipCode: "2100" },
      { name: "Cupang Proper", zipCode: "2100" },
      { name: "Doña Francisca", zipCode: "2100" },
      { name: "Gugo", zipCode: "2100" },
      { name: "Lanatan", zipCode: "2100" },
      { name: "Lote", zipCode: "2100" },
      { name: "Munting Batangas", zipCode: "2100" },
      { name: "Pag-asa", zipCode: "2100" },
      { name: "Puerto Rivas Ibaba", zipCode: "2100" },
      { name: "Puerto Rivas Itaas", zipCode: "2100" },
      { name: "Salian", zipCode: "2100" },
      { name: "San Jose", zipCode: "2100" },
      { name: "Sibacan", zipCode: "2100" },
      { name: "Talaba", zipCode: "2100" },
      { name: "Tenejero", zipCode: "2100" },
    ],
  },
  {
    name: "Dinalupihan",
    barangays: [
      { name: "Aklan", zipCode: "2110" },
      { name: "Balsik", zipCode: "2110" },
      { name: "Bangal", zipCode: "2110" },
      { name: "Bayan-bayanan", zipCode: "2110" },
      { name: "Burgos", zipCode: "2110" },
      { name: "Capunitan", zipCode: "2111" },
      { name: "Daang Bago", zipCode: "2110" },
      { name: "Del Pilar", zipCode: "2110" },
      { name: "Happy Valley", zipCode: "2110" },
      { name: "Jose C. Payumo Jr.", zipCode: "2110" },
      { name: "Kalaklan", zipCode: "2110" },
      { name: "Luakan", zipCode: "2110" },
      { name: "Mabini Extension", zipCode: "2110" },
      { name: "Magsaysay", zipCode: "2110" },
      { name: "Naparing", zipCode: "2110" },
      { name: "Panilao", zipCode: "2110" },
      { name: "Pag-asa", zipCode: "2110" },
      { name: "Payangan", zipCode: "2110" },
      { name: "Pita", zipCode: "2110" },
      { name: "San Benito", zipCode: "2110" },
      { name: "San Isidro", zipCode: "2110" },
      { name: "San Pablo", zipCode: "2110" },
      { name: "San Ramon", zipCode: "2110" },
      { name: "Santa Isabel", zipCode: "2110" },
      { name: "Santo Niño", zipCode: "2110" },
      { name: "Tubo-tubo", zipCode: "2110" },
      { name: "Tucop", zipCode: "2110" },
      { name: "West Daang Bago", zipCode: "2110" },
    ],
  },
  {
    name: "Hermosa",
    barangays: [
      { name: "Almacen", zipCode: "2111" },
      { name: "Balsik", zipCode: "2111" },
      { name: "Daang Bago", zipCode: "2111" },
      { name: "Daang Pare", zipCode: "2111" },
      { name: "Ibaba", zipCode: "2111" },
      { name: "Mabini", zipCode: "2111" },
      { name: "Mambog", zipCode: "2111" },
      { name: "Palihan", zipCode: "2111" },
      { name: "Poblacion", zipCode: "2111" },
      { name: "San Pedro", zipCode: "2111" },
    ],
  },
  {
    name: "Limay",
    barangays: [
      { name: "Alangan", zipCode: "2103" },
      { name: "Alanginan", zipCode: "2103" },
      { name: "Cabog-Cabog", zipCode: "2103" },
      { name: "Carasuche", zipCode: "2103" },
      { name: "Duale", zipCode: "2103" },
      { name: "Lucanin", zipCode: "2103" },
      { name: "Maligaya", zipCode: "2103" },
      { name: "Malusac", zipCode: "2103" },
      { name: "Matayumtayum", zipCode: "2103" },
      { name: "Poblacion", zipCode: "2103" },
      { name: "Sta. Catalina", zipCode: "2103" },
    ],
  },
  {
    name: "Morong",
    barangays: [
      { name: "Antipolo", zipCode: "2108" },
      { name: "Binaritan", zipCode: "2108" },
      { name: "Liang", zipCode: "2108" },
      { name: "Nagbalayong", zipCode: "2108" },
      { name: "Poblacion", zipCode: "2108" },
      { name: "Saban Bajo", zipCode: "2108" },
      { name: "Saban Cuyo", zipCode: "2108" },
      { name: "Saban Laki", zipCode: "2108" },
      { name: "Sabanlangit", zipCode: "2108" },
      { name: "Saguing", zipCode: "2108" },
    ],
  },
  {
    name: "Orani",
    barangays: [
      { name: "Balut", zipCode: "2112" },
      { name: "Bayan", zipCode: "2112" },
      { name: "Calaguiman", zipCode: "2112" },
      { name: "Daungan", zipCode: "2112" },
      { name: "Ibaba", zipCode: "2112" },
      { name: "Kanawan", zipCode: "2112" },
      { name: "Kapunitan", zipCode: "2112" },
      { name: "Maligaya", zipCode: "2112" },
      { name: "Pandan", zipCode: "2112" },
      { name: "Poblacion", zipCode: "2112" },
      { name: "San Vicente", zipCode: "2112" },
      { name: "Tala", zipCode: "2112" },
    ],
  },
  {
    name: "Orion",
    barangays: [
      { name: "Daang Bago", zipCode: "2102" },
      { name: "Del Rosario", zipCode: "2102" },
      { name: "General Lim", zipCode: "2102" },
      { name: "Ibaba", zipCode: "2102" },
      { name: "Ibis", zipCode: "2102" },
      { name: "Kapunitan", zipCode: "2102" },
      { name: "Lati", zipCode: "2102" },
      { name: "Mabayo", zipCode: "2102" },
      { name: "Manuel L. Quezon", zipCode: "2102" },
      { name: "Poblacion", zipCode: "2102" },
      { name: "Puting Buhangin", zipCode: "2102" },
    ],
  },
  {
    name: "Pilar",
    barangays: [
      { name: "Almacen", zipCode: "2101" },
      { name: "Aluquin", zipCode: "2101" },
      { name: "Balut", zipCode: "2101" },
      { name: "Bayan-bayanan", zipCode: "2101" },
      { name: "Biaan", zipCode: "2101" },
      { name: "Cabcaben", zipCode: "2101" },
      { name: "Capaculan", zipCode: "2101" },
      { name: "Gomez", zipCode: "2101" },
      { name: "Liyang", zipCode: "2101" },
      { name: "Lucanin", zipCode: "2101" },
      { name: "Maligaya", zipCode: "2101" },
      { name: "Nagwaling", zipCode: "2101" },
      { name: "Poblacion", zipCode: "2101" },
      { name: "Rizal", zipCode: "2101" },
      { name: "Sisiman", zipCode: "2101" },
      { name: "Tala", zipCode: "2101" },
      { name: "Talaga", zipCode: "2101" },
      { name: "Tumagay", zipCode: "2101" },
      { name: "Wakas North", zipCode: "2101" },
      { name: "Wakas South", zipCode: "2101" },
    ],
  },
  {
    name: "Samal",
    barangays: [
      { name: "Calaguiman", zipCode: "2113" },
      { name: "Cataning", zipCode: "2113" },
      { name: "Daang Pare", zipCode: "2113" },
      { name: "Ibaba", zipCode: "2113" },
      { name: "Kanawan", zipCode: "2113" },
      { name: "Liang", zipCode: "2113" },
      { name: "Mabayo", zipCode: "2113" },
      { name: "Mabayuan", zipCode: "2113" },
      { name: "Mambog", zipCode: "2113" },
      { name: "Matiaba", zipCode: "2113" },
      { name: "Nagbalayong", zipCode: "2113" },
      { name: "Palihan", zipCode: "2113" },
      { name: "Pita", zipCode: "2113" },
      { name: "Sabang", zipCode: "2113" },
      { name: "Sabañgay", zipCode: "2113" },
      { name: "San Isidro", zipCode: "2113" },
      { name: "San Juan", zipCode: "2113" },
      { name: "San Pablo", zipCode: "2113" },
      { name: "Santa Lucia", zipCode: "2113" },
      { name: "Sapa", zipCode: "2113" },
      { name: "Sisiman", zipCode: "2113" },
      { name: "Tala", zipCode: "2113" },
      { name: "Talaon", zipCode: "2113" },
      { name: "Wawa", zipCode: "2113" },
    ],
  },
  {
    name: "Mariveles",
    barangays: [
      { name: "Alas-asin", zipCode: "2105" },
      { name: "Banawang", zipCode: "2105" },
      { name: "Baseco", zipCode: "2105" },
      { name: "Batangas II", zipCode: "2105" },
      { name: "Cabcaben", zipCode: "2105" },
      { name: "Camaya", zipCode: "2105" },
      { name: "Ipag", zipCode: "2105" },
      { name: "Lucanin", zipCode: "2105" },
      { name: "Malaya", zipCode: "2105" },
      { name: "Maligaya", zipCode: "2105" },
      { name: "Maloma", zipCode: "2105" },
      { name: "Mt. View", zipCode: "2105" },
      { name: "Poblacion", zipCode: "2105" },
      { name: "Sisiman", zipCode: "2105" },
      { name: "Sta. Rita", zipCode: "2105" },
      { name: "Top Bunkhouse", zipCode: "2105" },
    ],
  },
];

export default municipalitiesInBataan;
